---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: deployment-tolerations.yml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: k8s-cloud-system-webhook-server
      namespace: k8s-cloud-system
  - path: config-aks.yml
    target:
      version: v1
      kind: ConfigMap
      name: k8s-cloud-system-webhook-server
      namespace: k8s-cloud-system
  - path: job-tolerations.yml
    target:
      group: batch
      version: v1
      kind: Job
      name: webhook-certificate*
      namespace: k8s-cloud-system
