---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - 01-namespace.yml
patches:
  - path: ingress-patch.json
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: k8s-cloud-system-webhook-server
      namespace: k8s-cloud-system
  - path: deployment-resources.yml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: k8s-cloud-system-webhook-server
      namespace: k8s-cloud-system
