---
apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-certificate-create
  namespace: k8s-cloud-system
  labels:
    app.kubernetes.io/name: k8s-cloud-system
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/commponent: webhook-ca-bundle
    app.kubernetes.io/part-of: k8s-cloud-system
    app.kubernetes.io/managed-by: kubectl
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: webhook-certificate-admission-create
      labels:
        app.kubernetes.io/name: k8s-cloud-system
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/commponent: webhook-ca-bundle
        app.kubernetes.io/part-of: k8s-cloud-system
        app.kubernetes.io/managed-by: kubectl
    spec:
      containers:
        - name: create
          image: "registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794"
          imagePullPolicy: IfNotPresent
          args:
            - "create"
            - "--host=k8s-cloud-system,k8s-cloud-system.$(POD_NAMESPACE).svc,k8s-cloud-system.$(POD_NAMESPACE).svc.cluster.local"
            - "--namespace=$(POD_NAMESPACE)"
            - "--secret-name=k8s-cloud-system-webhook-ca-bundle"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccountName: k8s-cloud-system
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000

---
apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-certificate-patch
  namespace: k8s-cloud-system
  labels:
    app.kubernetes.io/name: k8s-cloud-system
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/commponent: webhook-ca-bundle
    app.kubernetes.io/part-of: k8s-cloud-system
    app.kubernetes.io/managed-by: kubectl
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: webhook-certificate-admission-patch
      labels:
        app.kubernetes.io/name: k8s-cloud-system
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/commponent: webhook-ca-bundle
        app.kubernetes.io/part-of: k8s-cloud-system
        app.kubernetes.io/managed-by: kubectl
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.azure.com/mode
                    operator: In
                    values:
                      - system
              weight: 1
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: kubernetes.azure.com/scalesetpriority
          value: "spot"
          operator: "Equal"
          effect: "NoSchedule"
      containers:
        - name: create
          image: "registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794"
          imagePullPolicy: IfNotPresent
          args:
            - "patch"
            - "--namespace=$(POD_NAMESPACE)"
            - "--secret-name=k8s-cloud-system-webhook-ca-bundle"
            - "--patch-failure-policy=Fail"
            - "--patch-mutating=true"
            - "--patch-validating=true"
            - "--webhook-name=k8s-cloud-system"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccountName: k8s-cloud-system
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
