---
apiVersion: v2
name: admission-controller-base
version: 0.0.1
appVersion: 0.0.1
kubeVersion: 1.26.3
description: A Helm chart to deploy the admission controller
type: application
keywords:
  - webhook
  - admission
  - controlller
home: https://github.com/blomquistr/admission-controller-base
sources:
  - https://github.com/blomquistr/admission-controller-base
dependencies:
  - name: ingress-nginx
    version: 4.6.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
maintainers:
  - name: Ryan Blomquist
    email: blomquist.r@gmail.com
    url: https://github.com/blomquistr
