---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cloud-system-webhook-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: webhook-server
          resources: {}
