---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cloud-system-webhook-server
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - defaultpool
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.azure.com/mode
                    operator: In
                    values:
                      - system
              weight: 100
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: k8s.mrll.com/app
                      operator: In
                      values:
                        - k8s-cloud-system
                    - key: k8s.mrll.com/component
                      operator: In
                      values:
                        - webhook-server
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: kubernetes.azure.com/scalesetpriority
          value: "spot"
          operator: "Equal"
          effect: NoSchedule
